---
--- Generated by Luanalysis
--- Created by kigawa.
--- DateTime: 2023/01/29 1:00
---
local NumChannel = {
    --- @return number
    getThrottle = function()
        return input.getNumber(1)
    end;
    --- @param value number
    setFuel = function(value)
        output.setNumber(2, value)
    end;
    --- @param value number
    setAir = function(value)
        output.setNumber(3, value)
    end;
}
local BoolChannel = {
    --- @return  boolean
    getKey = function()
        return input.getBool(1)
    end;
    --- @param value boolean
    setStarter = function(value)
        output.setBool(2, value)
    end;
}
local Property = {
    --- @field targetRps number
    minValue = property.getNumber("min value");
    --- @field targetRps number
    changeValue = property.getNumber("change value");
    --- @field targetRps number
    starterCount = property.getNumber("starter count");
    --- @field targetRps number
    startValue = property.getNumber("start value");
}
-- ---------------------------------------------------------
local Fuel = {
    MAX = 50
}
local currentFuel = Property.minValue
-- ---------------------------------------------------------
local ThrottlePosition = {
    CENTER = 0;
    BACK = 1;
    FOREWORD = 2;
}
--- @return 0 | 1 | 2
function ThrottlePosition.getPosition()
    local handle = NumChannel.getThrottle()
    if handle > 0 then
        return ThrottlePosition.FOREWORD
    end
    if handle < 0 then
        return ThrottlePosition.BACK
    end
    return ThrottlePosition.CENTER
end
-- ---------------------------------------------------------
local starterCount = 0

function onTick()
    local position = ThrottlePosition.getPosition()

    if not BoolChannel.getKey() then
        NumChannel.setAir(0)
        NumChannel.setFuel(0)
        starterCount = Property.starterCount
        BoolChannel.setStarter(false)
        return
    end

    if starterCount > 0 then
        starterCount = starterCount - 1
        BoolChannel.setStarter(true)
        NumChannel.setFuel(Property.startValue / 100)
        NumChannel.setAir((Property.startValue / 100) * 2)
        return
    else
        BoolChannel.setStarter(false)
    end

    if position == ThrottlePosition.CENTER then
        currentFuel = currentFuel - Property.changeValue
    else
        currentFuel = currentFuel + Property.changeValue
    end

    if currentFuel > Fuel.MAX then
        currentFuel = Fuel.MAX
    elseif currentFuel < Property.minValue then
        currentFuel = Property.minValue
    end

    NumChannel.setFuel(currentFuel / 100)
    NumChannel.setAir((currentFuel / 100) * 2)
end