---
--- Generated by Luanalysis
--- Created by kigawa.
--- DateTime: 2023/01/29 1:00
---
function getNumberProperty(label)
    return property.getNumber(label)
end
function getBool(channel)
    return input.getBool(channel)
end
function getNumber(channel)
    return input.getNumber(channel)
end
function setBool(channel, value)
    return output.setBool(channel, value)
end
function setNumber(channel, value)
    return output.setNumber(channel, value)
end
-- --------------------------------
local rpsChannel = 1
local gearStartChannel = getNumber(2)
local gearSize = getNumber(3)
local clutchChannel = 4

local accelerator = 1

local defaultThrottle = getNumberProperty("default throttle")
local throttleChangeMin = getNumberProperty("throttle change min")
local throttlePRate = getNumberProperty("throttle P rate")
local throttleIRate = getNumberProperty("throttle I rate")
local targetRps = getNumberProperty("target rps")
-- ------------------------------

function onTick()
    resetGear()
    if accelerator then
        setNumber(clutchChannel, 1)
    else
        setNumber(clutchChannel, 0)
    end

    local remainder = gear % gearSize + 1
    if not remainder == 0 then
        setBool(gearStartChannel + remainder - 1, true)
    end
end

function setTrue(channel)
    setBool(clutchChannel, true)
end

function resetGear()
    setBool(gear1, false)
    setBool(gear2, false)
    setBool(gear3, false)
    setBool(gear4, false)
end