---
--- Generated by Luanalysis
--- Created by kigaw.
--- DateTime: 2023/12/26 22:36
---
input  = {

  --- @return number
  --- @param channel number
  getNumber = function(channel) return 0 end;

  --- @param channel number
  --- @return boolean
  getBool   = function(channel) return true end;
}
property  = {

  --- @return number
  --- @param channel string
  getNumber = function(channel) return 0 end;

  --- @param channel string
  --- @return boolean
  getBool   = function(channel) return true end;
}
output = {

  --- @param channel number
  --- @param value number
  setNumber = function(channel, value) end;

  --- @param channel number
  --- @param value boolean
  setBool   = function(channel, value) end;
}